spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:maodien}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.root=INFO
logging.level.com.hainam.worksphere=DEBUG
logging.level.org.springframework.security=DEBUG

logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n

server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always